// <auto-generated />
using System;
using GREVocabulary.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GREVocabulary.Business.Migrations
{
    [DbContext(typeof(VocabularyHelperDbContext))]
    [Migration("20240411032644_SpacedRepetitionRelatedTablesCreated")]
    partial class SpacedRepetitionRelatedTablesCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("GREVocabulary.Business.EfCoreModels.SessionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Green")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Red")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpacedRepetitionSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordToMemorize")
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("Id");

                    b.HasIndex("SpacedRepetitionSessionId");

                    b.ToTable("SessionDetails");
                });

            modelBuilder.Entity("GREVocabulary.Business.EfCoreModels.SpacedRepetitionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Green")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Red")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpacedRepetitionSessions");
                });

            modelBuilder.Entity("GREVocabulary.Business.EfCoreModels.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordToMemorize")
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("GREVocabulary.Business.EfCoreModels.SessionDetail", b =>
                {
                    b.HasOne("GREVocabulary.Business.EfCoreModels.SpacedRepetitionSession", "SpacedRepetitionSession")
                        .WithMany("SessionDetails")
                        .HasForeignKey("SpacedRepetitionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpacedRepetitionSession");
                });

            modelBuilder.Entity("GREVocabulary.Business.EfCoreModels.SpacedRepetitionSession", b =>
                {
                    b.Navigation("SessionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
